//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FacultyModel", "students_fk", "Departments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVC.Models.Department), "student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVC.Models.student), true)]

#endregion

namespace MVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FacultyEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FacultyEntities2 object using the connection string found in the 'FacultyEntities2' section of the application configuration file.
        /// </summary>
        public FacultyEntities2() : base("name=FacultyEntities2", "FacultyEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FacultyEntities2 object.
        /// </summary>
        public FacultyEntities2(string connectionString) : base(connectionString, "FacultyEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FacultyEntities2 object.
        /// </summary>
        public FacultyEntities2(EntityConnection connection) : base(connection, "FacultyEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student> students
        {
            get
            {
                if ((_students == null))
                {
                    _students = base.CreateObjectSet<student>("students");
                }
                return _students;
            }
        }
        private ObjectSet<student> _students;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudents(student student)
        {
            base.AddObject("students", student);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FacultyModel", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="dep_id">Initial value of the Dep_id property.</param>
        /// <param name="dep_name">Initial value of the Dep_name property.</param>
        public static Department CreateDepartment(global::System.Int32 dep_id, global::System.String dep_name)
        {
            Department department = new Department();
            department.Dep_id = dep_id;
            department.Dep_name = dep_name;
            return department;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Dep_id
        {
            get
            {
                return _Dep_id;
            }
            set
            {
                if (_Dep_id != value)
                {
                    OnDep_idChanging(value);
                    ReportPropertyChanging("Dep_id");
                    _Dep_id = StructuralObject.SetValidValue(value, "Dep_id");
                    ReportPropertyChanged("Dep_id");
                    OnDep_idChanged();
                }
            }
        }
        private global::System.Int32 _Dep_id;
        partial void OnDep_idChanging(global::System.Int32 value);
        partial void OnDep_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Dep_name
        {
            get
            {
                return _Dep_name;
            }
            set
            {
                OnDep_nameChanging(value);
                ReportPropertyChanging("Dep_name");
                _Dep_name = StructuralObject.SetValidValue(value, false, "Dep_name");
                ReportPropertyChanged("Dep_name");
                OnDep_nameChanged();
            }
        }
        private global::System.String _Dep_name;
        partial void OnDep_nameChanging(global::System.String value);
        partial void OnDep_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dep_Description
        {
            get
            {
                return _Dep_Description;
            }
            set
            {
                OnDep_DescriptionChanging(value);
                ReportPropertyChanging("Dep_Description");
                _Dep_Description = StructuralObject.SetValidValue(value, true, "Dep_Description");
                ReportPropertyChanged("Dep_Description");
                OnDep_DescriptionChanged();
            }
        }
        private global::System.String _Dep_Description;
        partial void OnDep_DescriptionChanging(global::System.String value);
        partial void OnDep_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Dep_photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Dep_photo);
            }
            set
            {
                OnDep_photoChanging(value);
                ReportPropertyChanging("Dep_photo");
                _Dep_photo = StructuralObject.SetValidValue(value, true, "Dep_photo");
                ReportPropertyChanged("Dep_photo");
                OnDep_photoChanged();
            }
        }
        private global::System.Byte[] _Dep_photo;
        partial void OnDep_photoChanging(global::System.Byte[] value);
        partial void OnDep_photoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FacultyModel", "students_fk", "student")]
        public EntityCollection<student> students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<student>("FacultyModel.students_fk", "student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<student>("FacultyModel.students_fk", "student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FacultyModel", Name="student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student object.
        /// </summary>
        /// <param name="student_id">Initial value of the student_id property.</param>
        /// <param name="student_name">Initial value of the student_name property.</param>
        public static student Createstudent(global::System.Int32 student_id, global::System.String student_name)
        {
            student student = new student();
            student.student_id = student_id;
            student.student_name = student_name;
            return student;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 student_id
        {
            get
            {
                return _student_id;
            }
            set
            {
                if (_student_id != value)
                {
                    Onstudent_idChanging(value);
                    ReportPropertyChanging("student_id");
                    _student_id = StructuralObject.SetValidValue(value, "student_id");
                    ReportPropertyChanged("student_id");
                    Onstudent_idChanged();
                }
            }
        }
        private global::System.Int32 _student_id;
        partial void Onstudent_idChanging(global::System.Int32 value);
        partial void Onstudent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String student_name
        {
            get
            {
                return _student_name;
            }
            set
            {
                Onstudent_nameChanging(value);
                ReportPropertyChanging("student_name");
                _student_name = StructuralObject.SetValidValue(value, false, "student_name");
                ReportPropertyChanged("student_name");
                Onstudent_nameChanged();
            }
        }
        private global::System.String _student_name;
        partial void Onstudent_nameChanging(global::System.String value);
        partial void Onstudent_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String student_Address
        {
            get
            {
                return _student_Address;
            }
            set
            {
                Onstudent_AddressChanging(value);
                ReportPropertyChanging("student_Address");
                _student_Address = StructuralObject.SetValidValue(value, true, "student_Address");
                ReportPropertyChanged("student_Address");
                Onstudent_AddressChanged();
            }
        }
        private global::System.String _student_Address;
        partial void Onstudent_AddressChanging(global::System.String value);
        partial void Onstudent_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> student_Age
        {
            get
            {
                return _student_Age;
            }
            set
            {
                Onstudent_AgeChanging(value);
                ReportPropertyChanging("student_Age");
                _student_Age = StructuralObject.SetValidValue(value, "student_Age");
                ReportPropertyChanged("student_Age");
                Onstudent_AgeChanged();
            }
        }
        private Nullable<global::System.Int32> _student_Age;
        partial void Onstudent_AgeChanging(Nullable<global::System.Int32> value);
        partial void Onstudent_AgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Dep_id
        {
            get
            {
                return _Dep_id;
            }
            set
            {
                OnDep_idChanging(value);
                ReportPropertyChanging("Dep_id");
                _Dep_id = StructuralObject.SetValidValue(value, "Dep_id");
                ReportPropertyChanged("Dep_id");
                OnDep_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Dep_id;
        partial void OnDep_idChanging(Nullable<global::System.Int32> value);
        partial void OnDep_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ssn
        {
            get
            {
                return _ssn;
            }
            set
            {
                OnssnChanging(value);
                ReportPropertyChanging("ssn");
                _ssn = StructuralObject.SetValidValue(value, "ssn");
                ReportPropertyChanged("ssn");
                OnssnChanged();
            }
        }
        private Nullable<global::System.Int32> _ssn;
        partial void OnssnChanging(Nullable<global::System.Int32> value);
        partial void OnssnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String teacher
        {
            get
            {
                return _teacher;
            }
            set
            {
                OnteacherChanging(value);
                ReportPropertyChanging("teacher");
                _teacher = StructuralObject.SetValidValue(value, true, "teacher");
                ReportPropertyChanged("teacher");
                OnteacherChanged();
            }
        }
        private global::System.String _teacher;
        partial void OnteacherChanging(global::System.String value);
        partial void OnteacherChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FacultyModel", "students_fk", "Departments")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("FacultyModel.students_fk", "Departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("FacultyModel.students_fk", "Departments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("FacultyModel.students_fk", "Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("FacultyModel.students_fk", "Departments", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
